all: 01_signal, 02_pipe, 03_socket

01_signal:
	gcc -o 01_signal 01_signal.c 

02_pipe:
	gcc -o 02_pipe 02_pipe.c 

03_socket:
	gcc -o 03_socket 03_socket.c 

clean:
	rm -rf 01_signal 02_pipe 03_socket
